schema_version = "1.0.0"

id             = "DissolveNSpace_Tool"
version        = "2.3.1"
name           = "Dissolve & Space Tool"
tagline        = "Blender addon for dissolving a vertex selection while preserving overall shapes. Requires LoopTools"
maintainer     = "WheeNg"
type           = "add-on"

website = "https://github.com/Whee745/Dissolve-n-Space-Tool"

tags = ["Mesh", "Modeling"]

blender_version_min = "4.2.0"

license = ["SPDX:GPL-3.0-or-later"]

copyright = ["2026 WheeNg"]

[build]
paths_exclude_pattern = [
    "__pycache__/",
    ".git/",
    "*.zip",
]
